#include <gba.h>
#include "build/herm.h"   // generated by grit from assets/herm.png

static inline void dmaCopy16(const void* src, void* dst, u32 countHalfwords) {
    DMA3COPY(src, dst, DMA16 | countHalfwords);
}

int main(void) {
    irqInit();
    irqEnable(IRQ_VBLANK);

    // Mode 0, enable OBJ (sprites) with 1D tile mapping
    REG_DISPCNT = MODE_0 | OBJ_ENABLE | OBJ_1D_MAP;

    // Load Herm's 16-color OBJ palette (hermPal / hermPalLen are from grit)
    dmaCopy16(hermPal, SPRITE_PALETTE, hermPalLen / 2);

    // Copy 4bpp tile data into OBJ VRAM (CHARBLOCK 4: 0x6010000)
    dmaCopy16(hermTiles, (void*)CHAR_BASE_BLOCK(4), hermTilesLen / 2);

    // Hide all sprites first
    for (int i = 0; i < 128; i++) OAM[i].attr0 = ATTR0_DISABLE;

    // Show Herm as a 32x32 sprite at (120, 80)
    OBJATTR *herm = &OAM[0];
    herm->attr0 = ATTR0_4BPP | ATTR0_SQUARE | (80 & 0xFF);
    herm->attr1 = ATTR1_SIZE_32 | (120 & 0x1FF);
    herm->attr2 = 0 | (0 << 12); // tile index 0, palette bank 0

    // Simple idle loop (VBlank sync)
    while (1) VBlankIntrWait();
    return 0;
}
