#include <gba.h>
#include "herm.h"  // found via -Ibuild

int main(void) {
    // Set up the display in Mode 3 (bitmap mode) with BG2 enabled
    REG_DISPCNT = MODE_3 | BG2_ON;

    // Fill the screen with a green background
    u16* videoBuffer = (u16*)0x06000000;
    for (int y = 0; y < 160; y++) {
        for (int x = 0; x < 240; x++) {
            videoBuffer[y * 240 + x] = RGB5(0, 31, 0); // bright green
        }
    }

    // Draw Herm sprite from hermBitmap[] generated by grit
    int hermWidth = hermBitmapWidth;   // from herm.h
    int hermHeight = hermBitmapHeight; // from herm.h
    int startX = (240 - hermWidth) / 2;
    int startY = (160 - hermHeight) / 2;

    const unsigned short* img = hermBitmap;

    for (int y = 0; y < hermHeight; y++) {
        for (int x = 0; x < hermWidth; x++) {
            u16 color = img[y * hermWidth + x];
            if (color != RGB5(0, 31, 0)) { // skip background green
                videoBuffer[(startY + y) * 240 + (startX + x)] = color;
            }
        }
    }

    // Infinite loop
    while (1) {
        VBlankIntrWait();
    }

    return 0;
}
